name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

    - name: Set PKG_CONFIG_PATH
      run: sudo sh -c "echo /usr/lib/x86_64-linux-gnu/pkgconfig > /etc/ld.so.conf.d/gtk3.conf && ldconfig"

    - name: Build
      run: go build -v -o ./build/md-dns-changer ./cmd/md-dns-changer

    - name: Test
      run: go test -v ./...

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dns-changer-build-artifacts
        path: |
          ./build
