name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Set PKG_CONFIG_PATH
        run: sudo sh -c "echo /usr/lib/x86_64-linux-gnu/pkgconfig > /etc/ld.so.conf.d/gtk3.conf && ldconfig"

      - run: go build .
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: dns-changer
          # A file, directory or wildcard pattern that describes what to upload
          path: dns-changer
          # The desired behavior if no files are found using the provided path.

